site_name: CodeScoring Docs
site_url: https://docs.codescoring.ru/
theme:
  name: material
  logo: assets/codescoring_logo.png
  favicon: assets/favicon/favicon-32x32.png
  features:
    - navigation.sections
    - navigation.expand

plugins:
  - search

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Начало: index.md
  - Общая информация:
    - Поддержка пакетных менеджеров: supported-package-managers.md
    - Пути анализа и исключения: analysis-ignore-paths.md
  - Установка on-premise:
    - Требования к серверу: on-premise/server-requirements.md
    - Установка системы: on-premise/installation.md
    - Обновление системы: on-premise/update.md
    - Работа с логами: on-premise/logs.md
    - В случае проблем: on-premise/troubleshooting.md
  - Начало работы с on-premise:
    - Ввод ключа активации: on-premise/how-to/activation.md
    - Подключение системы контроля версий: on-premise/how-to/vcs-git.md
    - Создание собственников (proprietors): on-premise/how-to/proprietors.md
    - Создание категорий проектов: on-premise/how-to/categories.md
    - Создание проектов: on-premise/how-to/projects.md
    - Настройка политик: on-premise/how-to/policies.md
    - Запуск анализа: on-premise/how-to/launch-analysis.md
