site_name: CodeScoring Docs
site_url: https://docs.codescoring.com/
theme:
  name: material
  logo: assets/codescoring_logo.png
  favicon: assets/favicon/favicon-32x32.png
  features:
    - navigation.sections
    - navigation.expand

plugins:
  - search

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Начало: index.md
  - Общая информация:
    - Поддержка пакетных менеджеров: supported-package-managers.md
    - Пути анализа и исключения: analysis-ignore-paths.md
  - On-premise версия:
    - Требования к серверу: on-premise/server-requirements.md
    - Установка системы: on-premise/installation.md
    - Обновление системы: on-premise/update.md
    - Работа с логами: on-premise/logs.md
    - В случае проблем: on-premise/troubleshooting.md
    # - Начало использования: on-premise/getting-started.md