site_name: Публичная документация CodeScoring
site_url: https://docs.codescoring.ru/
theme:
  name: material
  language: ru
  logo: assets/codescoring_logo.png
  favicon: assets/favicon/favicon-32x32.png
  features:
    - navigation.tracking
    - navigation.expand
    - navigation.indexes

copyright: Copyright &copy; 2018 - 2023 Profiscope

plugins:
  - search
  - print-site

markdown_extensions:
  - attr_list
  - def_list
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra_css:
  - stylesheets/extra.css

nav:
  - Общая информация:
    - Начало: index.md
    - Функциональные характеристики: functionality.md
    - Этапы интеграции: integration-stages.md
    - Поддержка пакетных менеджеров: supported-package-managers.md
    - Changelog: changelog.md
  - CodeScoring Firewall: 
      - firewall/index.md
      - NXRM Firewall: firewall/nexus_firewall.md
      - JFrog Firewall: firewall/jfrog_firewall.md
  - Установка on-premise:
    - Требования к серверу: on-premise/server-requirements.md
    - Установка системы: on-premise/installation.md
    - Обновление системы: on-premise/update.md
    - Резервное копирование: on-premise/backup.md
    - Работа с логами: on-premise/logs.md
    - Работа через прокси: on-premise/proxy.md
    - Самоподписные SSL сертификаты: on-premise/self-signed-ssl.md
    - Пути анализа и исключения: on-premise/analysis-ignore-paths.md
    - В случае проблем: on-premise/troubleshooting.md
    - Работа системы в Kubernetes: on-premise/installation-in-k8s.md
  - Начало работы с on-premise:
    - Ввод ключа активации: on-premise/how-to/activation.md
    - Создание владельцев: on-premise/how-to/proprietors.md
    - Подключение системы контроля версий: on-premise/how-to/vcs-git.md
    - Создание категорий проектов: on-premise/how-to/categories.md
    - Настройка проектов: on-premise/how-to/projects.md
    - Настройка политик: on-premise/how-to/policies.md
    - Запуск анализа: on-premise/how-to/launch-analysis.md
    - Управление учетными записями: on-premise/how-to/users.md
    - Настройка Email: on-premise/how-to/email-settings.md
    - Настройка LDAP: on-premise/how-to/ldap-settings.md
    - Настройка интеграции с Jira: on-premise/how-to/jira.md
    - Работа с консольным агентом: on-premise/how-to/cli-agent.md
    - Работа с визуализацией графов зависимостей: on-premise/how-to/graphs.md
    - Настройка уведомлений: on-premise/how-to/notifications.md
    - Работа с API: on-premise/how-to/api.md
    - Настройка метрик: on-premise/how-to/metrics.md
